### ISSUE TITLE
Scope not being set

### ISSUE THREAD

**Issue by Jmrich** [AuraEQ/laravel-multi-tenant#52]
Using Laravel 5 and followed instructions as they are listed except for the config file which gave me error. No scope is being set on the queries and I can access another tenants information.
\TenantScope::addTenant('company_id', \Auth::user()->company_id);
I currently have this in the login function. Not sure if docs are up to date for L5

**Comment by Jmrich** [comment]
Added scope to middleware, and it is being set. Another issue came up when doing a query on the company table since it is looking for the company_id column on the company table which just has the id column.
Auth::user()->company->name
select * from `companies` where companies.company_id = '3' and `companies`.`id` = 3

**Comment by Jmrich** [comment]
Added scope to middleware to work properly. Tried adding once user logged in but was not applied. Noticed when doing queries on relationships it will check the $tenantColumn twice:
"query" => "select * from `clients` where clients.hospital_id = '3' and `clients`.`hospital_id` = ? and `clients`.`hospital_id` is not null"
Not sure if its a big deal or not.

**Comment by patroniton** [comment]
I had something similar happen to me with Laravel 5.

I put the `TenantScope::addTenant('tenant_id', \Auth::user->tenant_id)` in my login function after a successful login. I check the `$tenants` array after this has been done and it says the tenant_id is in the array at position 0, which is expected.

However, on the next request, there is nothing in the `$tenants` array, so of course it doesn't use this to scope my queries.

I've done the same workaround as @Jmrich and put the `TenantScope::addTenant('tenant_id', \Auth::user->tenant_id)` in my Authenticate middleware so that it will happen on every request. I think this will work for now, but hopefully this is fixed in the future!

**Comment by HipsterJazzbo** [comment]
Yeah, `TenantScope::addTentant()` needs to be run on every request. I'm going to update the realm to make that more clear.
